"""Add quantity and unit to products

Revision ID: 7c462590d995
Revises: 408c9248c423
Create Date: 2025-09-18 18:25:46.321886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c462590d995'
down_revision: Union[str, Sequence[str], None] = '408c9248c423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('unit', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
