# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpiralGenerator
                                 A QGIS plugin
 This plugin creates spiral (similar to a loxodrome) LineStrings. Starting from a given coordinate, with given parameters, create 10 right and 10 left logarithmic spirals every 36 degrees, which pass through the Earth and end at the antipodal point of the starting coordinate.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-29
        copyright            : (C) 2025 by Victor Mulyungi
        email                : victorsonofmartin@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpiralGenerator class from file SpiralGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sSpiralgenerator import SpiralGenerator
    return SpiralGenerator(iface)
